name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3      

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3   
        with:
          node-version: 20
          cache: 'npm'                 

      - name: List directory contents for debugging
        run: |
          echo "Current directory:"
          ls -la
          echo "Source directory:"
          ls -la src/
          echo "Renderer directory:"
          ls -la src/renderer/
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: webpack-build-logs
          path: |
            dist/
            npm-debug.log
            yarn-debug.log
            yarn-error.log
